### ISSUE TITLE
can't work with TETRA plug in (radiorefrence one)

### ISSUE THREAD

**Issue by fe8769a** [GoranRadivojevic/sdrsharp-limesdr#3]
can't work with TETRA plug in (radiorefrence one)

no signal transfered to TETRA decoder

**Comment by GoranRadivojevic** [comment]
> 
> 
> can't work with TETRA plug in (radiorefrence one)
> 
> no signal transfered to TETRA decoder

This is an SDR# issue because not all frontend plugins are loaded with all options enabled. LimeSDR frontend plugin capability must be added directly to the source code of SDR# or as an option in the configuration file (famous "magic line"). Try to write to the author of SDR#.
