### ISSUE TITLE
Dont work with 1777 or 1784 version

### ISSUE THREAD

**Issue by bossco79** [GoranRadivojevic/sdrsharp-limesdr#5]
Dont work with 1777 or 1784 version, or I don't understand how to add a device. These versions are missing the config file FrontEnds.xml, when I create it according to the example - still there is no limesdr in the device selection menu.

**Comment by GoranRadivojevic** [comment]
You are right! It is working up to 1732 x86 version. It is corrected now.

**Comment by ccoenen** [comment]
Is there no way to load this in a more recent version? I just downloaded 1.0.0.1910 and ran into the same problem.

I tried adding the line to `bin/Plugins.xml` instead, but this did not get me anywhere.

**Comment by GoranRadivojevic** [comment]
You can't add new frontends in SDR# v1910, only program addons. Sorry but this is not because of me!

**Comment by ccoenen** [comment]
that's so sad.

Thank you for your effort!
